### PR TITLE
0.18.0-pre.1

### PR DESCRIPTION
**Pull request by ailisp**
Not draft, but also not intend for merge, only for review. 0.18.0 will be the branch we're using.

@matklad Is there a good way to test the published dependency on nearcore? Do we have to publish to test it?

### CODE REVIEW

**Comment by matklad** [comment]
I think the best way is to publish -- publishing `-pre` is cheap. Let me try to publish this...

**Comment by matklad** [comment]
Hm, something's not right with versions here, `cargo` doesn't upderstand the project structure:

```rust
λ cargo t
error: no matching package named `wasmer-runtime-core-near` found
location searched: /home/matklad/projects/wasmer/lib/runtime-core
prerelease package needs to be specified explicitly
wasmer-runtime-core-near = { version = "0.18.0-pre.1" }
required by package `wasmer v0.17.1 (/home/matklad/projects/wasmer/lib/api)`
```

Let's keep `cargo test` working, this'll help with applying future patches.

**Comment by ailisp** [comment]
@matklad Good point! seems like pre is different:
> prerelease package needs to be specified explicitly

So now I fixed cargo t and run cargo publish. But i'm not owner of wasmer-runtime-core-near, (and also wasmer-runtime-core, wasmer-runtime-singlepass, don't know if I'm owner, they're blocked by wasmer-runtime-core-near) can you add me? /cc @willemneal

**Comment by matklad** [comment]
published all three crates!

**Comment by ailisp** [comment]
Closed as it's published

**Pull request closed without merging**
