### PR TITLE
Disentangle UniversalArtifact from UniversalEngine

### LINKED ISSUE #8959: near-vm: Decouple UniversalArtifact from a specific instance of UniversalEngine

### PR DESCRIPTION
**Pull request by nagisa**
I recommend reviewing this commit-by-commit. Read the descriptions for each commit for underlying motivation behind the specific changes.

As a broader motivation, I believe this will make it more straightforward to implement 0-copy-deserialization as a follow-up.

Fixes https://github.com/near/nearcore/issues/8959

### CODE REVIEW

**Comment by matklad** [comment]
>which are instantiated multiple times, the performance will drop

This I think is pretty much our use-case, given the in-memory cache. How much of an impact we expect here in practice? Ie, if we call a fairly simple function (no-op) in a fairly complex contract (>1k functions, >mb total size) 1k times in a loop, what would be timing before-after?

**Comment by matklad** [comment]
Ie, it looks like maybe we need three public types here? 

a) a `Vec<u8>` which we store in the database, and which we can re-interpret as in-memory data structure (plus stuff like https://github.com/rust-lang/odht)
b) A "cooked" artifact, which takes this `Vec<u8>`, and computes some usual hash-tables on-top (but hopufuly not to many)
c) An instance

It seems that what we do here is move from `ab + c` to `a + bc`.

**Comment by nagisa** [comment]
> Ie, it looks like maybe we need three public types here?

I think these all already exist today, and more:

1. `[u8]` – serialized artifact – contains compiled machine code, tables, etc;
2. `Artifact` – a “deserialized” artifact, contains machine code, tables, etc. Also represents data allocated into `Engine` (e.g. published code mmaps);
3. `Engine`/`Store` – owns the memory maps allocated for the machine code contained within artifacts;
4. `Instance` – references the code mmaps owned by `Engine` + some additional tables (e.g. GOT-like table) that are produced as a result of linking.

> A "cooked" artifact, which takes this Vec<u8>, and computes some usual hash-tables on-top (but hopufuly not to many)
> [...]
> It seems that what we do here is move from ab + c to a + bc.

The problem isn't quite the hash tables as much as the fact that `Artifact` references state such as the `mmap`s of the machine code and the trampolines, which are tied to the lifetime of the engine.

We definitely want to move the responsibilities around, potentially introducing additional types to represent additional intermediate states. I expect the difference between 1 and 2 to blur a little as the features of `rkyv` are utilized better.

> How much of an impact we expect here in practice?

In the past measurements, faulting in pages for mmaps were ~20-30% of the whole time we spend when creating a fresh instance from a serialized `[u8]`.

---

Ideally I think we should look into API changes necessary to enable storing `Instance`s into the cache. I think the only change necessary to do so would be to enable passing in `VMContext` for each call separately, so that each execution could use its own gas counter, `VMLogic` object and so on without those being tied to the `Instance` specifically. This would among other things help with the `VMLogic`'s lifetime conundrum we have.

Or we could add an additional type to represent an loaded code but not linked into full instance yet:

1. `Engine::load(Artifact) -> UnlinkedInstance`, where `UnlinkedInstance` is effectively a full instance with its import table not populated yet;
2. Store in the cache pairs of `Engine` and `UnlinkedInstance`;
3. Populate the import table at function call time producing an `Instance` from `UnlinkedInstance`.

Either choice has potential to overall improve the performance of calling a function further due to the fact that e.g. relocations only need to be processed once, at load time (right now these are processed when an instance is created from an artifact).

---

I'm happy to continue pursuing these avenues before this PR merges. Stacked diffs are pretty cool.

**Comment by matklad** [comment]
>Ideally I think we should look into API changes necessary to enable storing Instances into the cache.

Hm, this intuitively feels not right to me. I think instance is a short-lived object we want to create per function call, and we generally want to keep instances independent. Ie, it seems that instance is exactly what's different between two wasm invocations. 

I guess another question I have is that, after this PR, `UnviresalArtifact` **is** `SerializableModule`. Do we want to remove one of them? Or do we want to add more fields to `UnviresalArtifact` in the follow ups? 

It seems that perhaps `UniversalArtifact` *before* this PR is pretty-much `UnlinkedInstance`?

**Comment by nagisa** [comment]
> Hm, this intuitively feels not right to me. I think instance is a short-lived object we want to create per function call, and we generally want to keep instances independent. Ie, it seems that instance is exactly what's different between two wasm invocations.

I think I might agree broadly in that the name is wrong for what I'm looking to achieve. Today `Instance` is a concept present to encompass both the idempotent data relevant to the module as well as the mutable state between VM entries. All of our VM entries want effectively a fresh mutable state, and thus `Instance` isn't a concept that's super useful to us.

I was more broadly aiming at conveying that we should be looking at caching everything that's idempotent between VM entries (i.e. everything except the state), rather than recomputing some of it every time a `FunctionCall` occurs. In today's world that's somewhere between `UniversalArtifact` and `Instance`.

Once something representing this in-between exists, in my eyes `Instance` kind of loses most of its purpose, so I kind of ended up placing the resulting type in place of the old `Instance`. Hope that explains the misnomer ^^

> I guess another question I have is that, after this PR, UnviresalArtifact is SerializableModule. Do we want to remove one of them? Or do we want to add more fields to UnviresalArtifact in the follow ups?

`SerializableModule` is not public and `UniversalArtifact` is acting as a public interface here. The fact that former isn't inlined into the latter reduces some churn at least.

There is no reason to add any more fields to `UniversalArtifact` in the future from what I know.

> It seems that perhaps UniversalArtifact before this PR is pretty-much UnlinkedInstance?

Not quite – today `UniversalArtifact` is not linked, not relocated, its memories, tables and globals aren't allocated, and the frame info is not registered (this one in particular is curious, given that all the necessary information is known once the code pages are allocated during creation of the `UniversalArtifact`).

**Comment by nagisa** [comment]
I guess another clarification for why we want `UniversalArtifact` to be what is presented here – most of the types in `wasmer` are owned, so there isn't really a nice way to avoid a large number of allocations when we don't jump pretty much the entire way from “deserialized” to almost-instantiated in a single step.

In the future I expect `Artifact`s to gain a higher-kinded lifetime and that lifetime to be isolated to artifacts alone.

In some ways any kind of impedance mismatch in naming vs. intuition is likely entirely because I'm trying to retrofit 0-copy deserialization into the confines of the current API.

**Comment by matklad** [comment]
Yeah, I think there's some terminological not-on-the-same-pagness here. The way I see it, `Instance` is a wasm-spec concept: 

https://webassembly.github.io/spec/core/exec/runtime.html#module-instances

and I feel it is relatively important that what we call "Instance" matches what instance means in the spec. 

>In today's world that's somewhere between UniversalArtifact and Instance.

Uhu. I think this pretty matches the concept of `Module`.

**Review by matklad — APPROVED** [review]
Truth to be said, I am still not *entirely* convinced: 

* that moving stuff from artifact to instance is the right next step (as opposed to creating that intermediary) 
* that this won't regress our actual performance too much

But I think we can follow up on both cases later, so let's unblock! For perfomance especially, this'll be much easier to check when we have a corresponding nearcore PR with upgrade.

**Pull request closed without merging**
