### PR TITLE
Fix opcode cost

### PR DESCRIPTION
**Pull request by olonho**
To ensure that we will not overflow in fast gas counter on multiplication - add check in VM instantiation.

### CODE REVIEW

**Comment by nagisa** [comment]
Hm, I think this still runs into a risk of overflowing the gas cost during the intermediate multiplication calculation and miscounting the gas. In particular taking the [sample reproducer from before](https://github.com/near/wasmer/pull/64#discussion_r749539354), this is the assembly that we get:

```asm
   0x00007ffff54263c0: mov    0x128(%r15,%riz,1),%rax
   0x00007ffff54263c8: mov    0x10(%rax,%riz,1),%rcx
   0x00007ffff54263d0: mov    $0x64,%rdx
   0x00007ffff54263d7: rex    imul %edx,%ecx
   0x00007ffff54263db: mov    0x0(%rax,%riz,1),%rdx
   0x00007ffff54263e3: add    %rcx,%rdx
   0x00007ffff54263e6: jo     0x7ffff5426433
   0x00007ffff54263ec: cmp    %rdx,0x8(%rax,%riz,1)
   0x00007ffff54263f4: mov    %rdx,0x0(%rax,%riz,1)
   0x00007ffff54263fc: jbe    0x7ffff54264db
   0x00007ffff5426402: jmp    0x7ffff54263c0
```

For this specific example we multiply the provided opcode cost multiplier with the function argument (in this case a `0x64`) as passed in through the test wasm code. So e.g. even an opcode cost of `0x28f5c29` is problematic as we'll ultimately count very little gas as an actual operation cost due to an overflow.

I don't know how the calls to the `gas` function end up materializing but at least to me the tests indicate to me that it may be called by anybody who wishes to do so?

**Comment by matklad** [comment]
> it may be called by anybody who wishes to do so? In that case it seems to me that making the implementation robust is the approach we must take.

Yeah, that's sadly true. `gas` is just a usual host function, and you can just call it: 

https://github.com/near/nearcore/blob/73bb54a7665e6aa0fa6bbd9930159a6669042a77/runtime/near-vm-runner/src/imports.rs#L364-L365

"Add intrinsics mechanism which isn't accessable to the contract itself" is on a todo list.

**Comment by olonho** [comment]
Not sure if it's a bug in our assembler or in disassembler you use. `rex    imul %edx,%ecx` looks wrong, it must be `imulq $rdx, rcx`.

**Comment by nagisa** [comment]
Since the we multiply 32-bit integers `imul %edx,%ecx` is the expected instruction. x64 ignores the `rex` prefix for 32 bit operations AFAIK. The dissassembler is gdb.

**Comment by olonho** [comment]
Reworked logic by just avoiding intrinsification in cases where we shouldn't do it.

**Comment by nagisa** [comment]
I think this is reasonable. Now that we verify that neither operand to multiply shall exceed `i32::MAX`, the multiplication itself can't overflow either.

**Pull request merged**
